# Generated by Django 3.0.2 on 2020-01-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piracyreport', '0002_csharp8'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=150)),
                ('date_found', models.DateField()),
                ('date_resolved', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='CSharp8',
        ),
    ]
