# Generated by Django 3.0.2 on 2020-01-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piracyreport', '0003_auto_20200116_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='date_found',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='date_resolved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
