# Generated by Django 3.0.2 on 2020-01-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piracyreport', '0004_auto_20200116_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Status',
            field=models.CharField(choices=[('Resolved', 'Resolved'), ('Unresolved', 'Unresolved')], default='Unresolved', max_length=20),
        ),
    ]
