# Generated by Django 3.0.2 on 2020-01-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piracyreport', '0005_auto_20200117_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=20)),
                ('Book_name', models.CharField(max_length=150)),
            ],
        ),
    ]
